export const mockDbData = {
  patients: [
    {
      id: 1,
      name: "Eleanor Whitmore",
      email: "eleanor@clarion.health",
      dateOfBirth: "1958-03-14",
      phone: "(617) 555-0148",
      memberSince: "2019-06-02",
      insurancePlan: "Harbor Blue PPO Gold",
      memberId: "HB-4482910",
      hsaBalanceCents: 184250,
      fsaBalanceCents: 61200,
      verified: true,
      allergies: "Penicillin, sulfa drugs",
    },
  ],
  stores: [
    {
      id: 1,
      name: "Clarion Union Square",
      address: "18 Summer Street",
      city: "Boston",
      state: "MA",
      zip: "02111",
      phone: "(617) 555-2100",
      hours: "Mon–Sat 8a–9p · Sun 9a–6p",
      waitMinutes: 8,
      hasColdChain: true,
      lat: 42.351,
      lng: -71.062,
      image: "/images/store.jpg",
    },
    {
      id: 2,
      name: "Clarion Brookline Clinical",
      address: "420 Harvard Street",
      city: "Brookline",
      state: "MA",
      zip: "02446",
      phone: "(617) 555-2244",
      hours: "Mon–Fri 7a–10p · Sat–Sun 8a–8p",
      waitMinutes: 12,
      hasColdChain: true,
      lat: 42.343,
      lng: -71.123,
      image: "/images/interior.jpg",
    },
  ],
  products: [
    {
      id: 1,
      slug: "clarion-cold-calm",
      name: "Clarion Cold Calm Syrup",
      brand: "Clarion Clinical",
      category: "otc",
      subcategory: "Cough & Cold",
      priceCents: 1899,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 86,
      image: "/images/cold.jpg",
      shortDescription:
        "Night-and-day dual formula for cough, congestion, and scratchy throat without the groggy hangover.",
      usage: "Use at the first sign of a cold. Shake well. Measure with the included clinical cup only.",
      dosage: "Adults 12+: 10 mL every 6 hours. Do not exceed 40 mL in 24 hours.",
      warnings:
        "Do not combine with other dextromethorphan products. Ask a pharmacist before use if you have high blood pressure, glaucoma, or take MAOIs.",
      activeIngredients: "Dextromethorphan HBr 20 mg / 10 mL; Guaifenesin 200 mg / 10 mL; Phenylephrine HCl 5 mg / 10 mL",
      interactions: "May potentiate sedating antihistamines. Caution with SSRIs (serotonin syndrome risk).",
      clinicalNotes:
        "Expectorant plus cough suppressant pairing is indicated for productive cough with residual irritation. Phenylephrine dose is conservative for elderly patients.",
      clinicalTrials:
        "Open-label 2023 n=412 community pharmacy study: 71% reported sleep continuity improvement at night 2 versus baseline cough diary.",
      rating: 4.7,
      reviewCount: 312,
      symptomTags: "cough,cold,congestion,sore throat",
    },
    {
      id: 2,
      slug: "harbor-ibuprofen",
      name: "Harbor Relief Ibuprofen 200 mg",
      brand: "Harbor Relief",
      category: "otc",
      subcategory: "Pain Relief",
      priceCents: 1299,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 140,
      image: "/images/pills-blue.jpg",
      shortDescription: "Rapid-onset NSAID tablets for musculoskeletal pain, dental ache, and fever.",
      usage: "Take with food or milk. Swallow whole with a full glass of water.",
      dosage: "Adults: 1–2 tablets every 4–6 hours. Max 6 tablets (1200 mg) in 24 hours unless directed.",
      warnings:
        "NSAID warning: may cause stomach bleeding. Do not use in the third trimester of pregnancy. Avoid if you have had an ulcer, kidney disease, or are taking blood thinners without clinician review.",
      activeIngredients: "Ibuprofen 200 mg",
      interactions:
        "Increased bleeding with anticoagulants, omega-3 at high dose, and SSRIs. Attenuates ACE-inhibitor antihypertensive effect; monitor renal function.",
      clinicalNotes:
        "COX-1/COX-2 nonselective NSAID. Prefer acetaminophen first-line in patients over 65 with cardiovascular disease unless inflammation is primary.",
      clinicalTrials:
        "Cochrane review of ibuprofen 200–400 mg for acute pain: NNT 2.7 for 50% pain relief versus placebo at 6 hours.",
      rating: 4.6,
      reviewCount: 890,
      symptomTags: "pain,fever,headache,inflammation",
    },
    {
      id: 3,
      slug: "aether-cetirizine",
      name: "Aether Allergy Cetirizine 10 mg",
      brand: "Aether",
      category: "otc",
      subcategory: "Allergy",
      priceCents: 1599,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 210,
      image: "/images/pills-white.jpg",
      shortDescription: "Once-daily second-generation antihistamine for seasonal and perennial allergic rhinitis.",
      usage: "Take in the evening if drowsiness occurs. May be taken with or without food.",
      dosage: "Adults and children 6+: one 10 mg tablet daily.",
      warnings: "May cause drowsiness. Use caution when driving. Reduce dose in severe renal impairment.",
      activeIngredients: "Cetirizine HCl 10 mg",
      interactions: "Additive CNS depression with alcohol, magnesium at high dose, and other sedating agents.",
      clinicalNotes:
        "Low blood-brain-barrier penetration relative to first-generation antihistamines. Onset typically 20–60 minutes.",
      clinicalTrials:
        "Pivotal SAR trials showed 46–52% reduction in total nasal symptom score versus placebo over 2 weeks.",
      rating: 4.8,
      reviewCount: 654,
      symptomTags: "allergy,sneezing,itchy eyes,hay fever",
    },
    {
      id: 4,
      slug: "northline-first-aid",
      name: "Northline Compact First Aid Kit",
      brand: "Northline",
      category: "otc",
      subcategory: "First Aid",
      priceCents: 3499,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 54,
      image: "/images/first-aid.jpg",
      shortDescription: "ANSI-aligned compact kit with sterile dressings, antiseptic, and trauma shears.",
      usage: "Keep in a dry, accessible place. Replace any opened sterile item immediately after use.",
      dosage: "Not a medication. Follow included wound-care card for minor cuts and burns.",
      warnings: "Not a substitute for emergency care. Call 911 for uncontrolled bleeding, chest pain, or loss of consciousness.",
      activeIngredients: "Sterile gauze, adhesive dressings, antiseptic wipes (benzalkonium chloride 0.13%), nitrile gloves",
      interactions: "None.",
      clinicalNotes: "Meets workplace first-aid minimums for a 10-person office. Includes a burn gel sachet.",
      clinicalTrials: "N/A — device/kit.",
      rating: 4.9,
      reviewCount: 188,
      symptomTags: "cut,burn,first aid,injury",
    },
    {
      id: 5,
      slug: "lumen-thermometer",
      name: "Lumen Clinical Digital Thermometer",
      brand: "Lumen",
      category: "otc",
      subcategory: "First Aid",
      priceCents: 2499,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 77,
      image: "/images/thermometer.jpg",
      shortDescription: "Fast-reading clinical thermometer with memory and fever-alert guidance.",
      usage: "Place under the tongue or armpit. Read after the beep.",
      dosage: "Use as directed by the included guide. Not for continuous monitoring.",
      warnings: "Do not use on infants under 2 months without clinician advice.",
      activeIngredients: "Digital thermometer device",
      interactions: "None.",
      clinicalNotes: "High-precision sensor with 0.1°C resolution for rapid triage.",
      clinicalTrials: "In-home study: median measurement time 7 seconds.",
      rating: 4.8,
      reviewCount: 210,
      symptomTags: "fever,monitor,temperature,care",
    },
    {
      id: 6,
      slug: "wellpath-vitamin-d",
      name: "WellPath Vitamin D3 + K2",
      brand: "WellPath",
      category: "wellness",
      subcategory: "Vitamins",
      priceCents: 2199,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 65,
      image: "/images/serum.jpg",
      shortDescription: "Daily immune and bone support with a clinician-guided dosing profile.",
      usage: "Take once daily with a meal containing fat.",
      dosage: "1 softgel daily. Do not exceed 2000 IU without consultation.",
      warnings: "Use caution with calcium supplements or anticoagulants.",
      activeIngredients: "Vitamin D3 2000 IU; Vitamin K2 90 mcg",
      interactions: "May augment coagulopathy risk in patients on warfarin; monitor INR.",
      clinicalNotes: "Supports bone metabolism and immune health in patients with low vitamin D exposure.",
      clinicalTrials: "Meta-analysis: cholecalciferol supplementation improved serum 25(OH)D in 85% of participants over 12 weeks.",
      rating: 4.7,
      reviewCount: 421,
      symptomTags: "immune,bone health,vitamin d,wellness",
    },
  ],
  patientMedications: [
    {
      id: 1,
      patientId: 1,
      productId: 1,
      name: "Clarion Cold Calm Syrup",
      nextDoseAt: "Tonight at 8:00 PM",
      reminderEnabled: true,
      remainingDoses: 18,
      refillDue: false,
      instructions: "Take 10 mL every 6 hours as needed for cough or congestion.",
    },
  ],
  prescriptions: [
    {
      id: 1,
      patientId: 1,
      sessionId: "guest",
      fileName: "eleanor-annual-rx.pdf",
      imagePath: "/images/prescription.png",
      ocrText: "Atorvastatin 20 mg once daily",
      status: "approved",
      medicationName: "Atorvastatin",
      dosage: "20 mg",
      prescriber: "Dr. Elena Ruiz",
      ndc: "12345-678-90",
      refillsRemaining: 2,
      nextRefillAt: "2026-10-15",
      copayCents: 1250,
      coinsurancePct: 15,
      createdAt: new Date("2026-09-01T09:00:00.000Z"),
    },
  ],
  refillSchedules: [
    {
      id: 1,
      patientId: 1,
      prescriptionId: 1,
      frequency: "Monthly",
      deliveryMethod: "Courier",
      active: true,
    },
  ],
  consultations: [
    {
      id: 1,
      patientId: 1,
      sessionId: "guest",
      type: "telehealth",
      scheduledAt: "2026-09-04 18:00",
      status: "open",
      topic: "Seasonal allergy review",
      pharmacistName: "Dr. Maya Chen",
      createdAt: new Date("2026-09-04T17:30:00.000Z"),
    },
  ],
  messages: [
    {
      id: 1,
      consultationId: 1,
      sender: "pharmacist",
      body: "I can review the allergy plan and make sure it won’t conflict with your current meds.",
      createdAt: new Date("2026-09-04T17:31:00.000Z"),
    },
  ],
  orders: [
    {
      id: 1,
      patientId: 1,
      sessionId: "guest",
      status: "review",
      fulfillment: "pickup",
      storeId: 1,
      subtotalCents: 1899,
      hsaCents: 0,
      fsaCents: 0,
      personalCents: 1899,
      dobVerified: true,
      consultAcknowledged: true,
      timeline: "Queued for pharmacist review",
      createdAt: new Date("2026-09-03T14:00:00.000Z"),
    },
  ],
  orderItems: [
    {
      id: 1,
      orderId: 1,
      productId: 1,
      quantity: 1,
      priceCents: 1899,
      billingBucket: "personal",
    },
  ],
  cartItems: [
    {
      id: 1,
      sessionId: "guest",
      productId: 1,
      quantity: 1,
      billingBucket: "personal",
    },
  ],
  drugInteractions: [
    {
      id: 1,
      productAId: 1,
      productBId: 2,
      severity: "moderate",
      description: "Cold and pain reliever combination can increase GI irritation risk.",
      recommendation: "Avoid combining multiple NSAIDs and watch for stomach discomfort.",
    },
  ],
  expenses: [
    {
      id: 1,
      patientId: 1,
      label: "Annual flu vaccine",
      category: "preventive",
      amountCents: 4200,
      hsaCents: 4200,
      fsaCents: 0,
      occurredOn: "2026-08-25",
    },
  ],
};
