import { db } from "@/db";
import {
  drugInteractions,
  expenses,
  patientMedications,
  patients,
  prescriptions,
  products,
  refillSchedules,
  stores,
} from "@/db/schema";

let seeded = false;

export async function ensureSeed() {
  if (seeded) return;
  const existing = await db.select({ id: products.id }).from(products).limit(1);
  if (existing.length > 0) {
    seeded = true;
    return;
  }

  await db.insert(patients).values([
    {
      name: "Eleanor Whitmore",
      email: "eleanor@clarion.health",
      dateOfBirth: "1958-03-14",
      phone: "(617) 555-0148",
      memberSince: "2019-06-02",
      insurancePlan: "Harbor Blue PPO Gold",
      memberId: "HB-4482910",
      hsaBalanceCents: 184250,
      fsaBalanceCents: 61200,
      verified: true,
      allergies: "Penicillin, sulfa drugs",
    },
  ]);

  await db.insert(stores).values([
    {
      name: "Clarion Union Square",
      address: "18 Summer Street",
      city: "Boston",
      state: "MA",
      zip: "02111",
      phone: "(617) 555-2100",
      hours: "Mon–Sat 8a–9p · Sun 9a–6p",
      waitMinutes: 8,
      hasColdChain: true,
      lat: 42.351,
      lng: -71.062,
      image: "/images/store.jpg",
    },
    {
      name: "Clarion Brookline Clinical",
      address: "420 Harvard Street",
      city: "Brookline",
      state: "MA",
      zip: "02446",
      phone: "(617) 555-2244",
      hours: "Mon–Fri 7a–10p · Sat–Sun 8a–8p",
      waitMinutes: 12,
      hasColdChain: true,
      lat: 42.343,
      lng: -71.123,
      image: "/images/interior.jpg",
    },
    {
      name: "Clarion Harbor Cold-Chain Hub",
      address: "90 Northern Avenue",
      city: "Boston",
      state: "MA",
      zip: "02210",
      phone: "(617) 555-0190",
      hours: "Open 24 hours · Clinical courier desk",
      waitMinutes: 4,
      hasColdChain: true,
      lat: 42.353,
      lng: -71.044,
      image: "/images/shelves.jpg",
    },
    {
      name: "Clarion Back Bay",
      address: "501 Boylston Street",
      city: "Boston",
      state: "MA",
      zip: "02116",
      phone: "(617) 555-0188",
      hours: "Mon–Sat 9a–8p · Sun 10a–5p",
      waitMinutes: 18,
      hasColdChain: false,
      lat: 42.35,
      lng: -71.076,
      image: "/images/pharmacy-modern.jpg",
    },
  ]);

  await db.insert(products).values([
    {
      slug: "clarion-cold-calm",
      name: "Clarion Cold Calm Syrup",
      brand: "Clarion Clinical",
      category: "otc",
      subcategory: "Cough & Cold",
      priceCents: 1899,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 86,
      image: "/images/cold.jpg",
      shortDescription:
        "Night-and-day dual formula for cough, congestion, and scratchy throat without the groggy hangover.",
      usage: "Use at the first sign of a cold. Shake well. Measure with the included clinical cup only.",
      dosage: "Adults 12+: 10 mL every 6 hours. Do not exceed 40 mL in 24 hours.",
      warnings:
        "Do not combine with other dextromethorphan products. Ask a pharmacist before use if you have high blood pressure, glaucoma, or take MAOIs.",
      activeIngredients: "Dextromethorphan HBr 20 mg / 10 mL; Guaifenesin 200 mg / 10 mL; Phenylephrine HCl 5 mg / 10 mL",
      interactions: "May potentiate sedating antihistamines. Caution with SSRIs (serotonin syndrome risk).",
      clinicalNotes:
        "Expectorant plus cough suppressant pairing is indicated for productive cough with residual irritation. Phenylephrine dose is conservative for elderly patients.",
      clinicalTrials:
        "Open-label 2023 n=412 community pharmacy study: 71% reported sleep continuity improvement at night 2 versus baseline cough diary.",
      rating: 4.7,
      reviewCount: 312,
      symptomTags: "cough,cold,congestion,sore throat",
    },
    {
      slug: "harbor-ibuprofen",
      name: "Harbor Relief Ibuprofen 200 mg",
      brand: "Harbor Relief",
      category: "otc",
      subcategory: "Pain Relief",
      priceCents: 1299,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 140,
      image: "/images/pills-blue.jpg",
      shortDescription: "Rapid-onset NSAID tablets for musculoskeletal pain, dental ache, and fever.",
      usage: "Take with food or milk. Swallow whole with a full glass of water.",
      dosage: "Adults: 1–2 tablets every 4–6 hours. Max 6 tablets (1200 mg) in 24 hours unless directed.",
      warnings:
        "NSAID warning: may cause stomach bleeding. Do not use in the third trimester of pregnancy. Avoid if you have had an ulcer, kidney disease, or are taking blood thinners without clinician review.",
      activeIngredients: "Ibuprofen 200 mg",
      interactions:
        "Increased bleeding with anticoagulants, omega-3 at high dose, and SSRIs. Attenuates ACE-inhibitor antihypertensive effect; monitor renal function.",
      clinicalNotes:
        "COX-1/COX-2 nonselective NSAID. Prefer acetaminophen first-line in patients over 65 with cardiovascular disease unless inflammation is primary.",
      clinicalTrials:
        "Cochrane review of ibuprofen 200–400 mg for acute pain: NNT 2.7 for 50% pain relief versus placebo at 6 hours.",
      rating: 4.6,
      reviewCount: 890,
      symptomTags: "pain,fever,headache,inflammation",
    },
    {
      slug: "aether-cetirizine",
      name: "Aether Allergy Cetirizine 10 mg",
      brand: "Aether",
      category: "otc",
      subcategory: "Allergy",
      priceCents: 1599,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 210,
      image: "/images/pills-white.jpg",
      shortDescription: "Once-daily second-generation antihistamine for seasonal and perennial allergic rhinitis.",
      usage: "Take in the evening if drowsiness occurs. May be taken with or without food.",
      dosage: "Adults and children 6+: one 10 mg tablet daily.",
      warnings: "May cause drowsiness. Use caution when driving. Reduce dose in severe renal impairment.",
      activeIngredients: "Cetirizine HCl 10 mg",
      interactions: "Additive CNS depression with alcohol, magnesium at high dose, and other sedating agents.",
      clinicalNotes:
        "Low blood-brain-barrier penetration relative to first-generation antihistamines. Onset typically 20–60 minutes.",
      clinicalTrials:
        "Pivotal SAR trials showed 46–52% reduction in total nasal symptom score versus placebo over 2 weeks.",
      rating: 4.8,
      reviewCount: 654,
      symptomTags: "allergy,sneezing,itchy eyes,hay fever",
    },
    {
      slug: "northline-first-aid",
      name: "Northline Compact First Aid Kit",
      brand: "Northline",
      category: "otc",
      subcategory: "First Aid",
      priceCents: 3499,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 54,
      image: "/images/first-aid.jpg",
      shortDescription: "ANSI-aligned compact kit with sterile dressings, antiseptic, and trauma shears.",
      usage: "Keep in a dry, accessible place. Replace any opened sterile item immediately after use.",
      dosage: "Not a medication. Follow included wound-care card for minor cuts and burns.",
      warnings: "Not a substitute for emergency care. Call 911 for uncontrolled bleeding, chest pain, or loss of consciousness.",
      activeIngredients: "Sterile gauze, adhesive dressings, antiseptic wipes (benzalkonium chloride 0.13%), nitrile gloves",
      interactions: "None.",
      clinicalNotes: "Meets workplace first-aid minimums for a 10-person office. Includes a burn gel sachet.",
      clinicalTrials: "N/A — device/kit.",
      rating: 4.9,
      reviewCount: 188,
      symptomTags: "cut,burn,first aid,injury",
    },
    {
      slug: "lumen-thermometer",
      name: "Lumen Clinical Digital Thermometer",
      brand: "Lumen",
      category: "otc",
      subcategory: "First Aid",
      priceCents: 2499,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 77,
      image: "/images/flu.jpg",
      shortDescription: "10-second oral/axillary thermometer with fever-flag backlight and memory recall.",
      usage: "Clean probe with alcohol before and after each use. Wait 15 minutes after hot or cold drinks.",
      dosage: "Single reading. Fever is generally ≥100.4°F (38°C) oral.",
      warnings: "Do not use rectally. Keep battery compartment away from children.",
      activeIngredients: "N/A — medical device",
      interactions: "None.",
      clinicalNotes: "±0.2°F accuracy in the clinical range. Suitable for household infectious-disease triage.",
      clinicalTrials: "Bench validation against NIST-traceable reference bath, 2024.",
      rating: 4.5,
      reviewCount: 241,
      symptomTags: "fever,flu,cold",
    },
    {
      slug: "softseal-bandages",
      name: "SoftSeal Sterile Adhesive Bandages",
      brand: "SoftSeal",
      category: "otc",
      subcategory: "First Aid",
      priceCents: 899,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 320,
      image: "/images/bandages.jpg",
      shortDescription: "Breathable, latex-free sterile strips in mixed sizes for everyday wounds.",
      usage: "Clean wound, dry thoroughly, apply without stretching skin.",
      dosage: "Change daily or when wet.",
      warnings: "Discontinue if rash develops. Seek care for wounds that gape, puncture, or show infection.",
      activeIngredients: "Non-woven backing, acrylate adhesive, absorbent pad",
      interactions: "None.",
      clinicalNotes: "Latex-free construction for atopic and occupational allergy patients.",
      clinicalTrials: "N/A — device.",
      rating: 4.4,
      reviewCount: 97,
      symptomTags: "cut,first aid,blister",
    },
    {
      slug: "pulsewell-bp",
      name: "Pulsewell Upper-Arm BP Monitor",
      brand: "Pulsewell",
      category: "chronic",
      subcategory: "Blood Pressure",
      priceCents: 7999,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 41,
      image: "/images/bp.jpg",
      shortDescription: "Clinically validated upper-arm cuff with dual-user memory and irregular-heartbeat flag.",
      usage: "Sit quietly 5 minutes. Cuff on bare left arm at heart level. Take two readings one minute apart.",
      dosage: "Measure at the same times daily. Log morning and evening averages.",
      warnings: "Not for neonatal use. Consult a clinician for readings ≥180/120 mmHg or symptoms of stroke.",
      activeIngredients: "N/A — medical device, cuff 22–42 cm",
      interactions: "None.",
      clinicalNotes: "Validated to ISO 81060-2. Irregular heartbeat detector is a screening flag, not a diagnostic ECG.",
      clinicalTrials: "ESH protocol validation, mean difference −1.4 / −0.9 mmHg versus mercury sphygmomanometer.",
      rating: 4.8,
      reviewCount: 520,
      symptomTags: "blood pressure,hypertension,heart",
    },
    {
      slug: "glucoguide-meter",
      name: "GlucoGuide Home Meter Kit",
      brand: "GlucoGuide",
      category: "chronic",
      subcategory: "Diabetes Supplies",
      priceCents: 5499,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 63,
      image: "/images/glucose.jpg",
      shortDescription: "No-coding glucometer kit with 25 strips, lancets, and 7-day pattern report.",
      usage: "Wash hands. Use side of fingertip. Apply a hanging drop to the strip window.",
      dosage: "Test as directed by your care plan — commonly fasting and 2 hours post-meal.",
      warnings: "Do not share lancet devices. Alternate-site testing may miss rapid glucose changes.",
      activeIngredients: "Glucose oxidase electrochemical strips",
      interactions: "High-dose vitamin C and uric acid may interfere with some oxidase strips.",
      clinicalNotes: "Meets ISO 15197:2013 accuracy. Pair with metformin or insulin therapy logs in the Patient Sanctuary.",
      clinicalTrials: "Capillary accuracy study n=164: 97.1% of results within ±15% of YSI reference.",
      rating: 4.6,
      reviewCount: 276,
      symptomTags: "diabetes,glucose,blood sugar",
    },
    {
      slug: "airwell-inhaler",
      name: "Airwell Respimat Soft-Mist Inhaler",
      brand: "Airwell",
      category: "chronic",
      subcategory: "Respiratory",
      priceCents: 12900,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: true,
      stock: 28,
      image: "/images/inhaler.jpg",
      shortDescription: "Prescription soft-mist inhaler for maintenance treatment of COPD and asthma (cartridge sold filled).",
      usage: "Prime if unused for 3 days. Exhale fully, seal lips, inhale slowly while pressing dose-release.",
      dosage: "Typical maintenance: 2 inhalations once daily. Follow your prescriber’s exact directions.",
      warnings: "Not a rescue inhaler. Seek emergency care for sudden breathing difficulty. Rinse mouth if steroid combination is used.",
      activeIngredients: "Tiotropium bromide 2.5 mcg / actuation (example cartridge)",
      interactions: "Additive anticholinergic effects with other muscarinic antagonists.",
      clinicalNotes:
        "Soft-mist platform improves lung deposition versus HFA MDI in patients with poor inspiratory force. Requires pharmacist technique check at first fill.",
      clinicalTrials:
        "UPLIFT-style long-acting anticholinergic data: reduced exacerbation rate versus placebo over 4 years in COPD cohorts.",
      rating: 4.7,
      reviewCount: 143,
      symptomTags: "asthma,copd,wheeze,breathing",
    },
    {
      slug: "oxypulse-oximeter",
      name: "OxyPulse Finger Oximeter",
      brand: "OxyPulse",
      category: "chronic",
      subcategory: "Diabetes Supplies",
      priceCents: 3299,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 90,
      image: "/images/oximeter.jpg",
      shortDescription: "Spot-check SpO2 and pulse rate meter for home respiratory monitoring.",
      usage: "Warm the finger. Remain still. Record the stable reading after the waveform settles.",
      dosage: "Use as directed during illness or known lung disease. SpO2 ≤92% warrants clinician contact.",
      warnings: "Nail polish, poor perfusion, and motion degrade accuracy. Not for continuous monitoring.",
      activeIngredients: "N/A — medical device",
      interactions: "None.",
      clinicalNotes: "Useful adjunct for COPD and post-viral home monitoring. Pair with thermometer for febrile illness.",
      clinicalTrials: "Arms comparison versus hospital pulse ox, mean absolute error 1.1% SpO2 in well-perfused adults.",
      rating: 4.5,
      reviewCount: 331,
      symptomTags: "breathing,oxygen,covid,copd",
    },
    {
      slug: "marine-omega",
      name: "Marine Omega-3 Clinical Softgels",
      brand: "Marine Clinical",
      category: "wellness",
      subcategory: "Supplements",
      priceCents: 2899,
      hsaEligible: false,
      fsaEligible: false,
      requiresColdChain: false,
      rxRequired: false,
      stock: 150,
      image: "/images/omega.jpg",
      shortDescription: "1,200 mg triglyceride-form EPA/DHA from anchovy oil, molecularly distilled.",
      usage: "Take with the largest meal of the day to reduce fish aftertaste.",
      dosage: "Two softgels daily, or as directed by a clinician.",
      warnings: "May increase bleeding tendency. Stop 7 days before surgery unless a clinician advises otherwise.",
      activeIngredients: "EPA 720 mg, DHA 480 mg per serving (triglyceride form)",
      interactions: "Additive antiplatelet effect with NSAIDs, warfarin, and high-dose garlic/ginkgo.",
      clinicalNotes:
        "Triglyceride form has superior bioavailability versus ethyl-ester in the absence of a high-fat meal. IFOS-tested for oxidation.",
      clinicalTrials:
        "REDUCE-IT used a purified EPA ethyl ester 4 g; this product is a lower-dose food-supplement analog, not a icosapent-ethyl substitute.",
      rating: 4.7,
      reviewCount: 701,
      symptomTags: "heart,inflammation,joints,cholesterol",
    },
    {
      slug: "solar-d3",
      name: "Solar D3 2,000 IU",
      brand: "Solar",
      category: "wellness",
      subcategory: "Supplements",
      priceCents: 1699,
      hsaEligible: false,
      fsaEligible: false,
      requiresColdChain: false,
      rxRequired: false,
      stock: 200,
      image: "/images/vitamins.jpg",
      shortDescription: "Cholecalciferol in olive-oil softgels for bone, immune, and mood support.",
      usage: "Take with a meal containing fat.",
      dosage: "One softgel daily. Recheck 25-OH vitamin D in 8–12 weeks if deficient.",
      warnings: "Do not exceed labeled dose without labs. Toxicity is rare but possible with megadosing.",
      activeIngredients: "Cholecalciferol 2,000 IU (50 mcg)",
      interactions: "Thiazide diuretics plus calcium may raise hypercalcemia risk.",
      clinicalNotes: "2,000 IU is an evidence-based maintenance dose for adults with limited sun exposure at northern latitudes.",
      clinicalTrials: "VITAL ancillary analyses: modest infection-risk reduction in those with baseline deficiency.",
      rating: 4.8,
      reviewCount: 412,
      symptomTags: "fatigue,bone,immune,vitamin d",
    },
    {
      slug: "night-magnesium",
      name: "Restorative Night Magnesium",
      brand: "Restorative",
      category: "wellness",
      subcategory: "Supplements",
      priceCents: 2199,
      hsaEligible: false,
      fsaEligible: false,
      requiresColdChain: false,
      rxRequired: false,
      stock: 118,
      image: "/images/capsules-jar.jpg",
      shortDescription: "Magnesium glycinate 200 mg elemental, formulated for evening calm and muscle recovery.",
      usage: "Take 30–60 minutes before bed.",
      dosage: "Two capsules nightly. Reduce if loose stools occur.",
      warnings: "Use caution in significant renal impairment. May potentiate sedating antihistamines.",
      activeIngredients: "Magnesium (as bisglycinate chelate) 200 mg",
      interactions: "Can decrease absorption of tetracyclines and bisphosphonates — separate by 2 hours.",
      clinicalNotes: "Glycinate form is better tolerated than oxide. Helpful in nocturnal leg cramps when serum Mg is low-normal.",
      clinicalTrials: "Small RCT n=46 insomnia: sleep efficiency +6% versus placebo at 2 weeks (exploratory).",
      rating: 4.6,
      reviewCount: 255,
      symptomTags: "sleep,cramp,stress,muscle",
    },
    {
      slug: "clinical-c-zinc",
      name: "Clinical C + Zinc",
      brand: "Clarion Clinical",
      category: "wellness",
      subcategory: "Supplements",
      priceCents: 1899,
      hsaEligible: false,
      fsaEligible: false,
      requiresColdChain: false,
      rxRequired: false,
      stock: 134,
      image: "/images/supplements.jpg",
      shortDescription: "Buffered ascorbic acid 1,000 mg with zinc picolinate 15 mg for immune season.",
      usage: "Take with food. Split dose if gastric upset occurs.",
      dosage: "One tablet daily. During a cold, a clinician may suggest short-term higher vitamin C — do not self-escalate zinc.",
      warnings: "Chronic zinc >40 mg/day can induce copper deficiency. High-dose C may interfere with some glucose strips.",
      activeIngredients: "Vitamin C 1,000 mg; Zinc 15 mg",
      interactions: "Zinc may reduce quinolone and tetracycline absorption.",
      clinicalNotes: "Useful during winter months. Not a substitute for influenza or COVID vaccination.",
      clinicalTrials: "Cochrane: vitamin C does not prevent colds in the general population but may shorten duration slightly.",
      rating: 4.4,
      reviewCount: 190,
      symptomTags: "immune,cold,fatigue",
    },
    {
      slug: "aurevia-serum",
      name: "Aurevia Barrier Repair Serum",
      brand: "Aurevia",
      category: "wellness",
      subcategory: "Medical-Grade Skincare",
      priceCents: 4200,
      hsaEligible: false,
      fsaEligible: false,
      requiresColdChain: false,
      rxRequired: false,
      stock: 72,
      image: "/images/serum.jpg",
      shortDescription: "Ceramide-dominant serum with 5% niacinamide for eczema-prone and retinoid-compromised skin.",
      usage: "Apply 3 drops to damp face morning and night. Follow with moisturizer and SPF in the day.",
      dosage: "Pea-sized amount twice daily.",
      warnings: "For external use only. Patch test for 48 hours if you have fragrance-triggered dermatitis (formula is fragrance-free).",
      activeIngredients: "Ceramide NP, AP, EOP; cholesterol; niacinamide 5%; hyaluronic acid",
      interactions: "Compatible with most topicals. Introduce slowly if stacking with prescription tretinoin.",
      clinicalNotes: "Mimics physiologic lipid ratio 3:1:1 ceramides:cholesterol:fatty acids used in atopic-dermatitis barrier repair.",
      clinicalTrials: "8-week investigator-blinded study n=62: 31% improvement in TEWL versus vehicle.",
      rating: 4.9,
      reviewCount: 88,
      symptomTags: "eczema,dry skin,barrier,redness",
    },
    {
      slug: "calendula-cream",
      name: "Calendula Medical Cream",
      brand: "Aurevia",
      category: "wellness",
      subcategory: "Medical-Grade Skincare",
      priceCents: 2400,
      hsaEligible: false,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: false,
      stock: 95,
      image: "/images/cream.jpg",
      shortDescription: "Medical-grade calendula and panthenol cream for cracked hands, post-procedure skin, and minor burns.",
      usage: "Apply a thin layer to clean, dry skin up to four times daily.",
      dosage: "Cover the affected area. Occlude only if directed.",
      warnings: "Avoid if allergic to Asteraceae (ragweed, chamomile). Not for deep puncture wounds.",
      activeIngredients: "Calendula officinalis flower extract 5%; panthenol 2%; petrolatum",
      interactions: "None systemic.",
      clinicalNotes: "Useful as a steroid-sparing emollient for irritant contact dermatitis in healthcare workers.",
      clinicalTrials: "Pilot burn-clinic series: faster re-epithelialization versus petrolatum alone on superficial partial-thickness burns.",
      rating: 4.7,
      reviewCount: 164,
      symptomTags: "dry skin,burn,rash,hands",
    },
    {
      slug: "lisinopril-10",
      name: "Lisinopril 10 mg Tablets",
      brand: "Clarion Rx",
      category: "chronic",
      subcategory: "Blood Pressure",
      priceCents: 1400,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: true,
      stock: 200,
      image: "/images/orange-bottles.jpg",
      shortDescription: "ACE inhibitor for hypertension and post-MI remodeling. Requires a valid prescription.",
      usage: "Take at the same time daily. Rise slowly from sitting. Monitor home blood pressure.",
      dosage: "Typical: 10 mg by mouth once daily. Do not adjust without your prescriber.",
      warnings:
        "Boxed: fetal toxicity. Stop if pregnancy is detected. May cause dry cough, hyperkalemia, or angioedema — seek emergency care for swelling of face or tongue.",
      activeIngredients: "Lisinopril 10 mg",
      interactions: "NSAIDs may blunt antihypertensive effect and worsen renal function. Potassium supplements and potassium-sparing diuretics raise hyperkalemia risk.",
      clinicalNotes:
        "First-line ACEI. Check BMP within 1–2 weeks of initiation or dose change. Cough occurs in ~5–20% and is not dose-dependent.",
      clinicalTrials: "HOPE, GISSI-3, and ALLHAT inform ACE-inhibitor outcome data in hypertension and high-risk vascular disease.",
      rating: 4.8,
      reviewCount: 94,
      symptomTags: "blood pressure,heart,hypertension",
    },
    {
      slug: "metformin-500",
      name: "Metformin 500 mg Tablets",
      brand: "Clarion Rx",
      category: "chronic",
      subcategory: "Diabetes Supplies",
      priceCents: 1200,
      hsaEligible: true,
      fsaEligible: true,
      requiresColdChain: false,
      rxRequired: true,
      stock: 240,
      image: "/images/pills-mix.jpg",
      shortDescription: "First-line oral therapy for type 2 diabetes. Requires a valid prescription.",
      usage: "Take with meals to reduce GI effects. Swallow whole. Do not crush ER formulations (this SKU is IR).",
      dosage: "Often 500 mg once or twice daily to start. Titrate per prescriber.",
      warnings:
        "Boxed: lactic acidosis (rare). Hold around iodinated contrast. Contraindicated if eGFR <30.",
      activeIngredients: "Metformin HCl 500 mg",
      interactions: "Iodinated contrast, excessive alcohol, carbonic anhydrase inhibitors increase lactic acidosis risk.",
      clinicalNotes: "Improves hepatic insulin sensitivity. Expect B12 decline with long-term use — monitor annually.",
      clinicalTrials: "UKPDS: metformin reduced all-cause mortality in overweight type 2 diabetes versus conventional therapy.",
      rating: 4.6,
      reviewCount: 121,
      symptomTags: "diabetes,glucose,blood sugar",
    },
  ]);

  const catalog = await db.select({ id: products.id, slug: products.slug }).from(products);
  const idBySlug = Object.fromEntries(catalog.map((row) => [row.slug, row.id]));

  await db.insert(drugInteractions).values([
    {
      productAId: idBySlug["harbor-ibuprofen"],
      productBId: idBySlug["marine-omega"],
      severity: "moderate",
      description:
        "Ibuprofen and high-dose omega-3 both impair platelet function. Combined use can increase bruising or GI bleeding risk.",
      recommendation:
        "A pharmacist review is required before this pairing ships. Consider acetaminophen for short-term pain if you take omega-3 daily.",
    },
    {
      productAId: idBySlug["harbor-ibuprofen"],
      productBId: idBySlug["lisinopril-10"],
      severity: "moderate",
      description:
        "NSAIDs may reduce lisinopril’s blood-pressure effect and, in older or volume-depleted patients, precipitate acute kidney injury.",
      recommendation:
        "Limit ibuprofen to the lowest dose and shortest duration. Have a pharmacist confirm recent kidney labs before checkout.",
    },
    {
      productAId: idBySlug["aether-cetirizine"],
      productBId: idBySlug["night-magnesium"],
      severity: "mild",
      description:
        "Cetirizine and magnesium glycinate can add together to cause drowsiness or slowed reaction time, especially in the evening.",
      recommendation:
        "Take cetirizine at night if you continue both. Do not drive until you know how the combination affects you.",
    },
    {
      productAId: idBySlug["clinical-c-zinc"],
      productBId: idBySlug["glucoguide-meter"],
      severity: "mild",
      description:
        "High-dose ascorbic acid can falsely elevate or suppress some glucose-oxidase strip readings.",
      recommendation:
        "If you take Clinical C, test with washed hands and mention the supplement if a reading seems unexpected.",
    },
  ]);

  await db.insert(prescriptions).values([
    {
      patientId: 1,
      sessionId: "seed",
      fileName: "cho-lisinopril-slip.jpg",
      imagePath: "/images/rx-pad.jpg",
      ocrText:
        "Dr. Helen Cho, MD · Harbor Cardiology\nRx: Lisinopril 10 mg tablet\nSig: Take one tablet by mouth daily\nQty: 90  Refills: 3\nDAW: No",
      status: "verified",
      medicationName: "Lisinopril 10 mg",
      dosage: "Take one tablet by mouth daily",
      prescriber: "Helen Cho, MD",
      ndc: "68180-0512-03",
      refillsRemaining: 3,
      nextRefillAt: "2026-04-18",
      copayCents: 700,
      coinsurancePct: 10,
    },
    {
      patientId: 1,
      sessionId: "seed",
      fileName: "patel-metformin-slip.jpg",
      imagePath: "/images/prescription.jpg",
      ocrText:
        "Dr. Anika Patel, MD · Brookline Endocrine\nRx: Metformin 500 mg tablet\nSig: Take one tablet by mouth twice daily with meals\nQty: 60  Refills: 5",
      status: "verified",
      medicationName: "Metformin 500 mg",
      dosage: "Take one tablet by mouth twice daily with meals",
      prescriber: "Anika Patel, MD",
      ndc: "0093-1074-01",
      refillsRemaining: 1,
      nextRefillAt: "2026-03-29",
      copayCents: 400,
      coinsurancePct: 10,
    },
    {
      patientId: 1,
      sessionId: "seed",
      fileName: "okonkwo-inhaler-slip.jpg",
      imagePath: "/images/stamp.jpg",
      ocrText:
        "Dr. Samuel Rhee, MD · Pulmonary\nRx: Airwell Respimat\nSig: Two inhalations once daily\nQty: 1 inhaler  Refills: 2",
      status: "review",
      medicationName: "Airwell Respimat",
      dosage: "Two inhalations once daily",
      prescriber: "Samuel Rhee, MD",
      ndc: "0597-0101-90",
      refillsRemaining: 2,
      nextRefillAt: "2026-04-02",
      copayCents: 3500,
      coinsurancePct: 20,
    },
  ]);

  await db.insert(refillSchedules).values([
    {
      patientId: 1,
      prescriptionId: 1,
      frequency: "every-90-days",
      deliveryMethod: "courier",
      active: true,
    },
    {
      patientId: 1,
      prescriptionId: 2,
      frequency: "every-30-days",
      deliveryMethod: "pickup",
      active: true,
    },
  ]);

  await db.insert(patientMedications).values([
    {
      patientId: 1,
      productId: idBySlug["lisinopril-10"],
      name: "Lisinopril 10 mg",
      nextDoseAt: "Tonight · 8:00 p.m.",
      reminderEnabled: true,
      remainingDoses: 18,
      refillDue: false,
      instructions: "One tablet daily. Hold and call if systolic BP is under 100 or you feel faint.",
    },
    {
      patientId: 1,
      productId: idBySlug["metformin-500"],
      name: "Metformin 500 mg",
      nextDoseAt: "Dinner · with food",
      reminderEnabled: true,
      remainingDoses: 9,
      refillDue: true,
      instructions: "One tablet with breakfast and dinner. Do not skip meals.",
    },
    {
      patientId: 1,
      productId: idBySlug["airwell-inhaler"],
      name: "Airwell Respimat",
      nextDoseAt: "Tomorrow morning",
      reminderEnabled: true,
      remainingDoses: 24,
      refillDue: false,
      instructions: "Two slow inhalations each morning. This is not a rescue inhaler.",
    },
  ]);

  await db.insert(expenses).values([
    {
      patientId: 1,
      label: "Lisinopril 90-day fill",
      category: "Prescription",
      amountCents: 700,
      hsaCents: 700,
      fsaCents: 0,
      occurredOn: "2026-01-12",
    },
    {
      patientId: 1,
      label: "Pulsewell BP Monitor",
      category: "Durable medical equipment",
      amountCents: 7999,
      hsaCents: 7999,
      fsaCents: 0,
      occurredOn: "2026-02-03",
    },
    {
      patientId: 1,
      label: "Marine Omega-3",
      category: "OTC supplement",
      amountCents: 2899,
      hsaCents: 0,
      fsaCents: 0,
      occurredOn: "2026-02-20",
    },
    {
      patientId: 1,
      label: "Pharmacist video consult",
      category: "Telehealth",
      amountCents: 0,
      hsaCents: 0,
      fsaCents: 0,
      occurredOn: "2026-03-01",
    },
  ]);

  seeded = true;
}
